### ISSUE TITLE
Please add some content

### ISSUE THREAD

**Issue by fclairamb** [gin-contrib/sessions#1]
Please add anything (like a README.md file) so that we can make a pull request and start migrating https://github.com/gin-gonic/contrib/tree/master/sessions here.

**Comment by appleboy** [comment]
@fclairamb Waiting this PR completely https://github.com/gin-gonic/contrib/issues/126. We will update https://github.com/gin-gonic/contrib Readme.

**Comment by appleboy** [comment]
@fclairamb Already updated.

https://github.com/gin-gonic/contrib/tree/master/sessions#eol-warning
