### ISSUE TITLE
Why vendoring ?

### ISSUE THREAD

**Issue by vedhavyas** [gin-contrib/sessions#13]
It is preferred not to store any 3rd party packages in vendor when you do not have any `main` package as this will lead to un-usability of this package.

Here is the issue I have faced. My repo does not vendor any packages.
```
/router.go:33: cannot use "github.com/gin-contrib/sessions".Sessions("cpsession", store) 
(type "github.com/gin-contrib/sessions/vendor/github.com/gin-gonic/gin".HandlerFunc) as 
type "github.com/gin-gonic/gin".HandlerFunc in argument to router.Use
```

**Comment by tboerger** [comment]
@appleboy it's fine to keep the vendor.json but please drop the rest of vendor.

**Comment by appleboy** [comment]
@tboerger I will fix this issue asap.
