### ISSUE TITLE
Maybe use a gopkg for gin-gonic?

### ISSUE THREAD

**Issue by vedhavyas** [gin-contrib/sessions#15]
Using tagged gin-gonic like `go get gopkg.in/gin-gonic/gin.v1` is much preferred since these releases are considered stable over current develop and also applications using this library and prefers gopkg will not have duplicate libs with different import paths

If agreed, can give a PR with the change

**Comment by tboerger** [comment]
@appleboy is working on replacing the gopkg.in import paths.

**Comment by appleboy** [comment]
@vedhavyas I recommend you replace `gopkg.in` with `github.com` now and we will update README on next version. I already update all gin middleware using  `github.com` as import path.
