### ISSUE TITLE
Any help on this error "Key github.com/gin-contrib/sessions does not exist"

### ISSUE THREAD

**Issue by thedevsaddam** [gin-contrib/sessions#19]
I am using [this](https://github.com/thedevsaddam/orchid/blob/master/vendor/app/config/session.go#L10-L28) function [here](https://github.com/thedevsaddam/orchid/blob/master/main.go#L40)
But when I use session in controller/handler it show the error "Key github.com/gin-contrib/sessions does not exist"

Controller code: 
```
session := sessions.Default(c)
		var count int
		v := session.Get("count")
		if v == nil {
			count = 0
		} else {
			count = v.(int)
			count++
		}
		session.Set("count", count)
		session.Save()
		c.JSON(200, gin.H{"count": count})
```

Any idea or help. Thanks in advance :)

**Comment by oceanchang** [comment]
Key "github.com/gin-contrib/sessions" does not exist

I have encountered this problem, how do you solve? thanx

**Comment by lhammond** [comment]
same problem here

**Comment by foobarfighter** [comment]
Hit this too.  Make sure you are importing the same library everywhere.  Use:

```"github.com/gin-contrib/sessions"```

and not:

```github.com/gin-gonic/contrib/sessions```

I had a mixture of the two in different files and it was causing problems.  Note the EOL warning on the README here:

https://github.com/gin-gonic/contrib/tree/master/sessions

**Comment by yaaaaashiki** [comment]
I have encounted same problem.
Probably, you forget to initialize cookie manager.
Should add following code in routeing point.

```go
r := gin.Default()
store := sessions.NewCookieStore([]byte("secret"))
r.Use(sessions.Sessions("mysession", store))
```

https://github.com/gin-contrib/sessions

**Comment by llakes** [comment]
For those still facing this same issue -- make sure you load the middleware ( r.Use(sessions.Sessions("mysession", store)) )  before others.
