### ISSUE TITLE
Remove archived gorilla packages 

### ISSUE THREAD

**Issue by VAISHAKH-GK** [gin-contrib/sessions#218]
There is few Gorilla web toolkit used in this project including gorilla/sessions and gorilla/securecookie.
From 9th December 2022 all Gorilla projects are archived so it would be better if all Archived Gorilla packages are removed.

**Comment by idc77** [comment]
What would you replace it with?

**Comment by Coachonko** [comment]
There are no viable alternatives, it's probably best to just rewrite including the archived gorilla/sessions functionality

**Comment by red-co** [comment]
gorilla is back supported,
https://github.com/gorilla
