### ISSUE TITLE
How to set the expire time with redis?

### ISSUE THREAD

**Issue by yb3616** [gin-contrib/sessions#24]
I can not find any options about to set the expire time from the godoc.
By the way, Does it support unix socket connection rather than tcp or udp?

**Comment by Melse** [comment]
for a store level ttl, set `MaxAge` value before `router.Use`, for example:
```go
store, _ := sessions.NewRedisStore(10, "tcp", "localhost:6379", "", []byte("your secret"))
store.Options(sessions.Options{MaxAge: 3600})
router.Use(sessions.Sessions("yoursession", store))
```

**Comment by snowdream** [comment]
> for a store level ttl, set `MaxAge` value before `router.Use`, for example:
> 
> ```go
> store, _ := sessions.NewRedisStore(10, "tcp", "localhost:6379", "", []byte("your secret"))
> store.Options(sessions.Options{MaxAge: 3600})
> router.Use(sessions.Sessions("yoursession", store))
> ```

Thank you, It works.

**Comment by jacobintern** [comment]
@snowdream hi,
Can I set MaxAge at this part ??

```go=
session := sessions.Default(c)
session.Set("test", 11223344)
session.Options(sessions.Options{MaxAge: 60})

session.Save()
```
but I try it, it doesn't work, so I have set this options to `Store`
