### ISSUE TITLE
how to know which client is who?

### ISSUE THREAD

**Issue by Celthi** [gin-contrib/sessions#38]
From the example, I know how to get the "count" from the session,
but how do I know which client is connect to the server?
For example, there are A and B user connect to the server. I suppose that I have to identify the connection is A or B.

**Comment by delphinus** [comment]
It should be store in sessions beforehand.  For instance, when user logs in, the server knows his/her username and password.  So the server can store the username into the session and uses it when he/she will access again.

**Comment by sensuikan1973** [comment]
I would like to see the sample code...

**Comment by delphinus** [comment]
Sorry for late.  I wrote a pseudo-code for this. https://github.com/gin-contrib/sessions/issues/42#issuecomment-390830910

> * What client sends to server ? What server send to client ?

It is the *cookie*.  All the clients/servers need to detect the sessions are the cookie.  But you need only `sessions.Default(c)` and this package catches the cookie, and prepares the valid session automatically.  (ref https://github.com/gin-contrib/sessions/issues/42#issuecomment-390836871)

**Comment by Celthi** [comment]
Thanks for all the replies.
