### ISSUE TITLE
type not registered for interface

### ISSUE THREAD

**Issue by leobuzhi** [gin-contrib/sessions#39]
```
if queryUser.CheckPassword(userData.Password) {
		if queryUser.Status == model.UserStatusInActive {
			encodedEmail := base64.StdEncoding.EncodeToString([]byte(queryUser.Email))
			c.JSON(http.StatusOK, gin.H{
				"retCode": model.SUCCESS,
				"retContent": gin.H{
					"email": encodedEmail,
				},
			})
			return
		}

		session := sessions.Default(c)

		session.Set("user", queryUser.ID)
		ok:=session.Save()
		log.Debug("save ok :%v",ok)
		c.JSON(http.StatusOK, gin.H{
			"retCode": model.SUCCESS,
			"retContent": gin.H{
				"data": queryUser,
			},
		})
	}
```
log print:
save ok :gob : type not registered for interface :model.User
why i cann't save it?only int ?

**Comment by delphinus** [comment]
Probably, your session has another property that contains `model.User` structs.  That is the reason.

**Comment by leobuzhi** [comment]
main.go
```
package main

import (
	"github.com/gin-contrib/sessions"
	"github.com/gin-gonic/gin"
	"github.com/name5566/leaf/log"
)

type Obj struct {
	a int
	b string
}

func main() {

	redisUrl := "127.0.0.1" + ":" + "6379"
	store, _ := sessions.NewRedisStore(10, "tcp", redisUrl, "")

	r := gin.Default()
	r.Use(sessions.Sessions("mysession", store))

	r.GET("/incr", func(c *gin.Context) {

		session := sessions.Default(c)

		obj := Obj{
			a: 1,
			b: "123",
		}

		session.Set("user", obj)
		ok := session.Save()
		log.Debug("save ok %v", ok)
		c.JSON(200, gin.H{
			"obj a": obj.a,
			"obj b": obj.b,
		})
	})
	r.Run(":8080")
}
```
I try a simple demo to set a object to session,it still log "save ok :gob : type not registered for interface :main.Obj".
@delphinus

**Comment by delphinus** [comment]
Yes, it is spec.  The `sessions` uses `gob` package in default, and `gob` needs initialization for encoding you own types.  See doc: https://golang.org/pkg/encoding/gob/#Register

And the doc says:

> Structs encode and decode only exported fields.

So you should use property names that starts with upper letters in structs.  Such as,

```go
type Obj struct {
  A int
  B string
}
```

**Comment by delphinus** [comment]
an exaple:

```go
func init() {
  gob.Register(Obj{})
}
```

**Comment by leobuzhi** [comment]
however,I add those code,it still doesn't work
```
func init() {
	gob.Register(model.User{})
}
```
log print:  securecookie: no codecs provided
so,I read the source code of session,it seem encode appear problem.
@delphinus

**Comment by delphinus** [comment]
You wrote below...

```go
store, _ := sessions.NewRedisStore(10, "tcp", redisUrl, "")
```

but `NewRedisStore` needs more arguments.

```go
func NewRedisStore(size int, network, address, password string, keyPairs ...[]byte) (RedisStore, error)
```

You are not supplying `keyPairs`.  Without this, `sessions` cannot work.  See doc about `NewRedisStore`.

**Comment by leobuzhi** [comment]
@delphinus 
thanks a lot ,it works.
