### ISSUE TITLE
kidstuff/mongostore is outdated

### ISSUE THREAD

**Issue by Newcratie** [gin-contrib/sessions#79]
It seems kidstuff/mongostore is outdated

# github.com/gin-contrib/sessions/mongo
../gin-contrib/sessions/mongo/mongo.go:15:40: cannot use c (type *"gopkg.in/mgo.v2".Collection) as type *"github.com/globalsign/mgo".Collection in argument to mongostore.NewMongoStore

**Comment by xiusin** [comment]
same

**Comment by appleboy** [comment]
I will take it.
