### ISSUE TITLE
import errors.

### ISSUE THREAD

**Issue by appleboy** [gin-contrib/sessions#8]
error:

> cannot use "github.com/goiotc/vendor/github.com/gin-contrib/sessions".Sessions("mysession", store) (type "github.com/goiotc/vendor/gopkg.in/gin-gonic/gin.v1".HandlerFunc) as type "github.com/goiotc/vendor/github.com/gin-gonic/gin".HandlerFunc in argument to router.Use

**Comment by umisama** [comment]
The gopkg.in is recommended by gin's README and other references.
Why do you use github.com/gin-gonic/gin on your application?

I think, sessions should be use gopkg.in.

**Comment by appleboy** [comment]
@umisama `gin` framework have another subpackage like `render` and `binding` so I think we can't recommend user to use `gopkg.in`.

![screen shot 2017-03-11 at 9 24 18 pm](https://cloud.githubusercontent.com/assets/21979/23823620/4071697c-06a1-11e7-9cb5-7d8640b775a4.png)

I think we will remove gopkg.in from readme on next version.

**Comment by umisama** [comment]
@appleboy OK, I understand the reason. 
I'll change my apps to using github from gopkg.

thanks!
