### ISSUE TITLE
cannot load github.com/ugorji/go/codec: ambiguous import: found .... in multiple modules

### ISSUE THREAD

**Issue by maerics** [gin-contrib/sessions#86]
I wanted to try the [cookie-based session example from the readme](https://github.com/gin-contrib/sessions#cookie-based) but it fails with the following error:

> cannot load github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:

To reproduce:

```bash
$ ls -l
total 0
$ go mod init foo
go: creating new go.mod: module foo
$ # copy cookie-based example code into the clipboard
$ pbpaste > ./main.go
$ go fmt ./main.go && go run ./main.go 
go: finding github.com/gin-contrib/sessions latest
go: finding github.com/gin-contrib/sessions/cookie latest
go: finding github.com/gin-gonic/gin v1.4.0
...
go: extracting github.com/gorilla/securecookie v1.1.1
build command-line-arguments: cannot load github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
	github.com/ugorji/go v1.1.4 (/Users/x/go/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
	github.com/ugorji/go/codec v0.0.0-20181209151446-772ced7fd4c2 (/Users/x/go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181209151446-772ced7fd4c2)
$ echo $?
1
```

I can't tell if this is an [issue with ugorji/go](https://github.com/ugorji/go/issues/291) or [cmd/go itself](https://github.com/golang/go/issues/29332) but thought I'd post here in case anyone knows of a fix. Will update if I find one.

**Comment by maerics** [comment]
Here's a [workaround found in ugorji/go#279](https://github.com/ugorji/go/issues/279#issuecomment-457676755):
```
go get github.com/ugorji/go@v1.1.2-0.20180831062425-e253f1f20942
```

**Comment by kuhufu** [comment]
I also encountered this problem.
gin latest version
in file `go.mod`
`github.com/ugorji/go/codec v0.0.0-20190204201341-e444a5086c43`
change to
`github.com/ugorji/go v1.1.4`
